name: Secret Detection

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan at midnight on Sunday

jobs:
  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GitLeaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          verbose: true
          fail-on-error: true  # This will make the workflow fail if secrets are found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}