name: Semgrep SAST Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly scan at midnight on Monday

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Semgrep Scan
        run: semgrep ci
        env:
          SEMGREP_RULES: >-
            p/golang
            p/security-audit
            p/secrets
          SEMGREP_TIMEOUT: 300